export const MASTER_TYPES = {
    ACCOUNT_GROUPS: 1,
    ACCOUNTS: 2,
    COST_CENTER_GROUPS: 3,
    COST_CENTERS: 4,
    CURRENCY_TYPE: 7,
    UNITS: 8, // KG, G, PCS , etc.
    TAX_TYPES: 9, // CHECK AGAIN
    COUNTRIES: 55,
    STATUS_ONE: 62, // SUCCESSFUL, UNSUCCESSFUL, CANCELLED.
    TITLES: 64, // Mr, Mrs, Miss, etc.
    STATUS_TWO: 65, // ACTIVE, HOLD, UNDER_PROCESS, PENDING.
}